### ISSUE TITLE
KL10: ITS peculiarities

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#117]
Making some notes for the future.

**Comment by larsbrinkhoff** [comment]
NTS DDT uses instructions like `XCT ",CFR` and expects the AC field to be ignored by the processor.

**Comment by larsbrinkhoff** [comment]
SALV sets EPT to 1000 but expects DTEFLG to remain at 444.

**Comment by rcornwell** [comment]
The AC field is ignored in user mode. In monitor mode it is PXCT instruction.

**Comment by larsbrinkhoff** [comment]
I'm guessing the ITS KL10 microcode has the AC field ignored in monitor mode too.

**Comment by larsbrinkhoff** [comment]
MC ITS had a device 500 called the KL-UDGE.  It works much like a combination of the KA10 lights (PI device) and PD clock.

**Comment by larsbrinkhoff** [comment]
I made a KL10 NTS DDT the obvious way, and it seems to work quite well.  I.e. cpu=KL10, RH10 disks, etc.  Wrote it out on a tape, and load -i'ed it.

Console I/O is fine.  Loading @ ITS off disk works.  It's still a KA10 ITS, so it does not run.

**Comment by rcornwell** [comment]
ITS now works on KL10A

**Comment by eswenson1** [comment]
Well, sort of.  You can now boot ITS, type Control-Z from T00, and get a HACTRN (DDT).  If you invoke :emacs directly, you get an emacs.  But if you first set the terminal type (so that it isn't a printing terminal), and set it to AAA, then you get an MUUO IN EXEC MODE fault.  (I typed :tctype aaa<enter> directly after getting HACTRN).  

But we are really close!  :-)

**Comment by larsbrinkhoff** [comment]
I think we have the peculiarities under control.  Closing.
