### ISSUE TITLE
KA-10:  Issues with mass storage devices on all available versions of TOPS-10.

### ISSUE THREAD

**Issue by PashPaw** [rcornwell/sims#181]
I've been trying to figure out some way to get some of the older DECUS submissions over to the 5-series monitor from TOPS-10 6.03 running on the KA-10 simulator because the only available tapes are in the BACKUP format.  So far, I haven't been very successful because I keep on running into errors with all the mass storage devices I've tried so far.  I'm using Ubuntu Linux 19.10 on x86-64 as a host.  The KA-10 simulator running 6.03 is using DPA for the system disks.

When I'm trying to create a scratch disk to restore the files on with the simulator and on unit DPA4, ONCE crashes after trying to refresh it:

`TYPE STR NAME TO BE REFRESHED(CR IF NONE, ALL IF ALL)
dcus

?CPU0 monitor error. stopcode name ZBC
?Aborting job

?CPU0 monitor error. stopcode name SOR
Reload monitor
`

TWICE doesn't like it either:

`DO YOU WANT TO CHANGE THE "SYS" SEARCH LIST?
Y
?
?Ill mem ref at user PC 005053`

I gave up and restored it to a single UFD on 6.03 and tried copying some files to DTA0 with mixed results on both 5.03 and 6.03.  On 6.03, it tries and does copy with the following error that seem to pop up randomly:

`.COPY DTA0:=*.DEM

device DTA000 OPR0 action requested`
`!
%Problem on device DTA000 for job 11`

On 5.03, it's a lot more consistent for both read and write and usually some sort of UUO error.  On write, I just got this:
`zero dta0:
?
?Error in job 1
?hung device DTA0; uuo at user 400433`

On read, it can do this:
`.copy dsk:=dta0:MORTGA.DEM

?Failure(s) during /X request`

And yes, this was after I tried copying it to MTA0 using FAILSA on 6.03.  It just gives me inconsistency errors when using it as 7-track drive, but I might need to look over some things too.

**Comment by rcornwell** [comment]
Not sure what is going wrong. I have created failsafe tapes on 6.03 and loaded them on 5.03. This is how I build the 5.03 monitor. There was some issues with 7 track drives. Try using the simulator in the kl10 branch. I will be pushing the kl10 branch to the main branch within the next few days, and then to the main simh tree hopefully be the end of the month. Try your tests on the kl10 branch, since this is the most current build.

`pdp10-ka tops603ka.ini 

KA-10 simulator V4.0-0 Current        git commit id: 67d859b3
/home/rich/pdp10/t603a/603/tops603ka.ini-2> at lpt  -n test.log
LPT: creating new file: test.log
/home/rich/pdp10/t603a/603/tops603ka.ini-10> at dpa4 dsk/ka_dskc0.rp3
DPA: creating new file
/home/rich/pdp10/t603a/603/tops603ka.ini-15> at dc 2020
Listening on port 2020
sim> bo dpa0



KA603 04-21-78
WHY RELOAD: hard
DATE: 4-21
TIME: 123

STARTUP OPTION: ?

CHANGE,DESTROY,GO,LONG,QUICK,NO INITIA,REFRESH,UNITID
/H FOR HELP

STARTUP OPTION: refresh
DPA4 FIRST HOM BLOCK CONSISTENCY ERROR
DPA4 SECOND HOM BLOCK CONSISTENCY ERROR

DO YOU WANT TO INITIALIZE THE HOME BLOCKS ON THIS UNIT?
y

%DPA5 IS OFF-LINE
DO YOU WANT IT TO BE 1)ON-LINE, 2)OFF-LINE, OR 3)DOWN? (TYPE #)

3

%DPA6 IS OFF-LINE
DO YOU WANT IT TO BE 1)ON-LINE, 2)OFF-LINE, OR 3)DOWN? (TYPE #)

^O
3

%DPA7 IS OFF-LINE
DO YOU WANT IT TO BE 1)ON-LINE, 2)OFF-LINE, OR 3)DOWN? (TYPE #)

3

%DPB0 IS OFF-LINE
DO YOU WANT IT TO BE 1)ON-LINE, 2)OFF-LINE, OR 3)DOWN? (TYPE #)

3

%DPB1 IS OFF-LINE
DO YOU WANT IT TO BE 1)ON-LINE, 2)OFF-LINE, OR 3)DOWN? (TYPE #)

3

%DPB2 IS OFF-LINE
DO YOU WANT IT TO BE 1)ON-LINE, 2)OFF-LINE, OR 3)DOWN? (TYPE #)

3

%DPB3 IS OFF-LINE
DO YOU WANT IT TO BE 1)ON-LINE, 2)OFF-LINE, OR 3)DOWN? (TYPE #)

3

%DPB4 IS OFF-LINE
DO YOU WANT IT TO BE 1)ON-LINE, 2)OFF-LINE, OR 3)DOWN? (TYPE #)

3

%DPB5 IS OFF-LINE
DO YOU WANT IT TO BE 1)ON-LINE, 2)OFF-LINE, OR 3)DOWN? (TYPE #)

3

%DPB6 IS OFF-LINE
DO YOU WANT IT TO BE 1)ON-LINE, 2)OFF-LINE, OR 3)DOWN? (TYPE #)

3

%DPB7 IS OFF-LINE
DO YOU WANT IT TO BE 1)ON-LINE, 2)OFF-LINE, OR 3)DOWN? (TYPE #)

3
DPA4 FIRST BAT BLOCK CONSISTENCY ERROR
DPA4 SECOND BAT BLOCK CONSISTENCY ERROR

DO YOU WANT A LIST OF BAD REGIONS?
yes

FIRST BLOCK      # BLOCKS

4179              1

DO YOU WANT TO INITIALIZE THE BAT BLOCKS ON THIS UNIT?
y

NOT NORMALLY DONE, ARE YOU SURE?
y
INITIALIZING BAT BLOCKS

BEFORE "HOME" BLOCKS ARE WRITTEN

TYPE STR NAME FOR A LIST OF ITS PARAMETERS(CR IF NONE, ALL IF ALL)


TYPE PHYSICAL UNIT NAME TO LIST ITS PARAMETERS(CR IF NONE, ALL IF ALL)


DO YOU WANT TO CHANGE ANY DISK PARAMETERS?(CR IF NO)
yes
TYPE STR NAME TO BE DISSOLVED(CR IF NONE, ALL IF ALL)

TYPE STR NAME TO BE DEFINED(CR IF NONE)
dskc
TYPE NAMES OF PHYSICAL UNITS IN STR(ALL IF ALL, EXTRA CR WHEN DONE)
dpa4

TYPE STR NAME TO BE DEFINED(CR IF NONE)


TYPE STR NAME TO CHANGE ITS PARAMETERS(CR IF NONE, ALL IF ALL)
dskc

AFTER EACH PRINTING OF CURRENT VALUE, TYPE NEW VALUE OR CR

PARAMETERS WHICH MAY BE CHANGED WITHOUT REFRESHING
# OF CONSECUTIVE BLOCKS TRIED FOR ON OUTPUT = 30
MIN = 1 MAX = 80000

SUM OF BLOCKS GUARANTEED TO USERS = 0
MIN = 0 MAX = 80000

# BLOCKS ALLOWED FOR OVERDRAW PER USER = 500
MIN = 0 MAX = 80000


IS THIS A PRIVATE STR? (TYPE Y IF PRIVATE, N IF NO ACCESS RESTRICTIONS)
n

PARAMETERS WHICH MAY NOT BE CHANGED WITHOUT REFRESHING
K FOR CRASH.EXE = 128
MIN = 0 MAX = 256
0

BLOCKS PER CLUSTER = 5
MIN = 1 MAX = 511

THEREFORE BITS PER CLUSTER ADR. = 14
THEREFORE BLOCKS PER SUPER-CLUSTER = 5
THEREFORE SUPER-CLUSTERS PER UNIT = 16000

BITS PER CLUSTER COUNT = 9
MIN = 1 MAX = 18

THEREFORE BITS PER CHECKSUM = 13

TYPE STR NAME TO CHANGE ITS PARAMETERS(CR IF NONE, ALL IF ALL)


TYPE PHYSICAL UNIT NAME TO CHANGE ITS PARAMETERS(CR IF NONE, ALL IF ALL)
dpa4

AFTER EACH PRINTING OF CURRENT VALUE, TYPE NEW VALUE OR CR

PARAMETERS WHICH MAY NOT BE CHANGED WITHOUT REFRESHING

ZERO UNIT ID - NEW ID NEEDED
dskc001

# OF SAT BLOCKS ON UNIT = 4
MIN = 4 MAX = 41
10

THEREFORE CLUSTERS PER SAT = 1600
THEREFORE WORDS PER SAT = 45

K FOR SWAPPING ON UNIT = 0
MIN = 0 MAX = 999
0


PARAMETERS WHICH MAY BE CHANGED WITHOUT REFRESHING
# SAT BLOCKS IN CORE = 1
MIN = 1 MAX = 10


TYPE PHYSICAL UNIT NAME TO CHANGE ITS PARAMETERS(CR IF NONE, ALL IF ALL)


UNITS IN ACTIVE SWAPPING LIST:
DPA0(0),DPA1(0),DPA2(0),DPA3(0)

DO YOU WANT TO CHANGE THE ACTIVE SWAPPING LIST?
n

STRS IN "SYS" SEARCH LIST:
DSKB

DO YOU WANT TO CHANGE THE "SYS" SEARCH LIST?
n

BEFORE "HOME" BLOCKS ARE WRITTEN

TYPE STR NAME FOR A LIST OF ITS PARAMETERS(CR IF NONE, ALL IF ALL)


TYPE PHYSICAL UNIT NAME TO LIST ITS PARAMETERS(CR IF NONE, ALL IF ALL)


DO YOU WANT TO CHANGE ANY DISK PARAMETERS?(CR IF NO)


HOME BLOCKS TO BE WRITTEN ON WHICH PHYSICAL UNITS (EXTRA CR WHEN THROUGH)
(CR IF NONE, ALL IF ALL ;"ALL" IS NORMAL CASE)
dpa4


HOME BLOCKS WRITTEN

DSK FILE STRUCTURES(STRS):
DSKB:DPA0(DKB001),DPA1(DKB002),DPA2(DKB003),DPA3(DKB004)
NEEDS REFRESHING DSKC:DPA4(DSKC00)

UNITS NOT IN A FILE STRUCTURE:
RPA0(),RPA1(),RPA2(),RPA3(),RPA4(),RPA5(),RPA6(),RPA7(),DPA5(),DPA6(),DPA7(),RPB0(),RPB1(),RPB2(),RPB3(),RPB4(),RPB5(),RPB6(),RPB7(),DPB0(),DPB1(),DPB2(),DPB3(),DPB4(),DPB5(),DPB6(),DPB7()

UNITS IN ACTIVE SWAPPING LIST:
DPA0(0),DPA1(0),DPA2(0),DPA3(0)

STRS IN "SYS" SEARCH LIST:
DSKB

TYPE STR NAME FOR A LIST OF ITS PARAMETERS(CR IF NONE, ALL IF ALL)


TYPE PHYSICAL UNIT NAME TO LIST ITS PARAMETERS(CR IF NONE, ALL IF ALL)


DO YOU WANT TO CHANGE ANY DISK PARAMETERS?(CR IF NO)



TYPE STR NAME TO BE REFRESHED(CR IF NONE, ALL IF ALL)
dsc\C\kc
TYPE STR NAME TO BE REFRESHED(CR IF NONE, ALL IF ALL)


STARTUP OPTION: quic
TO AUTOMATICALLY LOG-IN UNDER [1,2] TYPE "LOGIN"


KA603 1:27:01

.LOGIN 1,2

.RES
DSKB,DSKC,RPA0,RPA1,RPA2,RPA3,RPA4,RPA5,RPA6,RPA7,DPA5,DPA6,DPA7,RPB0,RP
B1,RPB2,RPB3,RPB4,RPB5,RPB6,RPB7,DPB0,DPB1,DPB2,DPB3,DPB4,DPB5,DPB6,DPB7
,CDP000,CDR000,PTR000,LPT000,DTA000,001,002,003,004,005,006,007,MTA000,0
01,002,003,004,005,006,007,PTP000

.SYSTAT

Status of KA603 at  1:27:21 on 21-Apr-78

Uptime 20, 99%Null time = 99%Idle + 0%Lost
1 Jobs in use out of 64.  1 logged in, 0 detached out of 64.  (LOGMAX)

Job    Who     Line#    What   Size(K)  State   Run Time

 1    [OPR]     CTY     SYSTAT  7+SPY   RN             0

Swapping space used = 0/512 = 0%
Virt. Core used = 7/512 = 1%
174K Core left
Active swapping ratio = 7/181 = 0.0
Average job size =7/1 = 7.0K+0/1 = 0.0K  Total=7/1 = 7.0K

No busy devices
1 disk DDBs

System File Structures:
Name    Free    Mount
DSKB    137267  1
DSKC    79650   0
Total Free 216917


.`

**Comment by rcornwell** [comment]
Please see if the problem occurs on the current master branch, KL10 support is now part of master, and this includes many changes to other devices.

**Comment by PashPaw** [comment]
So, the above instructions for the disk issues did work.  But, I think it might be an issue caused by throttling and it appears to only happen when it's throttling.

**Comment by rcornwell** [comment]
What throttling setting are you using, I would like to reproduce these issues.

**Comment by PashPaw** [comment]
set throttle 1M

**Comment by PashPaw** [comment]
This is 5.03's current configuration on my Linux box:

`set console log=run-%DATETIME%.log
set dpa0 rp02
at dpa0 -q dsk/dska0.rp1
at dpa1 dsk/dcus1.rp2
at lpt prt-%DATETIME%.lst
set cpu 128k
set throttle 1M
set dc modem=8
at dc 2503
expect "\r\n" send "SYSTEM\r"; continue
expect "DATE:" send  "%DATE_MM%-%DATE_DD%-71\r"; continue
expect "TIME:" send  "%TIME_HH%%TIME_MM%\r"; continue
expect -p " 1)ON-LINE, 2)OFF-LINE, OR 3)DOWN? " send -t after=50000 "3\r"; continue
boot dpa0
`

6.03 KA's (with DPA):

`set log boot-%DATETIME%.log
set throttle 1M
at lpt  prti-%DATETIME%.log
at dpa0 dsk/ka_dskb0.rp3
at dpa1 dsk/ka_dskb1.rp3
at dpa2 dsk/ka_dskb2.rp3
at dpa3 dsk/ka_dskb3.rp3
;at rpa0 dsk/ka_dskb0.rp6
;at rpa1 dsk/ka_dskb1.rp6
set mta type=b
set dc modem=8
set cpu 256k idle
at dc 2020`

**Comment by rcornwell** [comment]
I have been unable to reproduce the disk issue on a throttled machine. The Dectape is hard to get right since it is run free run mode when it seeks blocks. So throttle speed effects the seeking of blocks. Check out the current master build and see if it still has problems with disk or 7 track mag tapes.

**Comment by PashPaw** [comment]
Okay.  And that largely fixed the DECtape problem.  I've only seen one error so far but it does seem to behaving better.  Thanks for this and the KL10 sim.

**Comment by rcornwell** [comment]
Your welcome. Let me know if you find any more bugs.
