### ISSUE TITLE
KA10: Fix 340

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#190]
The 340 has some problems that should be fixed:

- There's a clr_interrupt missing which makes interrupts happen back-to-back.
- With this fixed, the transfer rate is much slower which makes the display flicker.
- The transfer rate can't be too high, or ITS will take notice and temporarily disable the display.
- Consider coscheduling the interrupts to reduce the load on the host.

**Comment by larsbrinkhoff** [comment]
FYI @philbudne

**Comment by larsbrinkhoff** [comment]
ITS has a parameter called MDISWD which is the maximum number of 36-bit words transferred to the 340 per half second.  It's set to 70000 octal, which means the maximum rate is 57344 words per second.  If this limit is reached, ITS will turn off the display for 300 (decimal) clock ticks.  This should be 5 seconds (but seems to be more like one second).

I don't know why this limit is in place.  It corresponds to 8 microseconds per 340 instruction, and almost all isntructions should take much longer.  Maybe it's to prevent really degenerate display lists like all zeros which are parameter mode no-op instructions.

With the current implementations, interrupts aren't cleared so words are sent back-to-back.  This does hit the limit easily which makes the display flicker badly.

**Comment by larsbrinkhoff** [comment]
Fixing the interrupts makes the transfer agree with the DPY device rate which is 500 microseconds per word.  This is a bit too slow for an acceptable refresh rate.  Maybe 100 would be more in the right ballpark, but then the load on the host is quite large.

I'm toying with an idea of a less accurate but less stressful mode where the DPY service calls are "coscheduled" with the clock interrupt running at 60 Hz.  Each such call would bulk transfer the right number of words to display.

**Comment by larsbrinkhoff** [comment]
I have tested my theory.  Fixing interrupt clearing and lowering the interval to 100 microseconds makes the display work much better.  All programs work fine under ITS and standalone, with two exceptions: timesharing Spacewar and SHRDLU TWDEMO.  They both draw and then pause for about one second.  But it's not due to the MDISWD limit.

**Comment by larsbrinkhoff** [comment]
Timing information from PDP-7 340 DISPLAY PROGRAMMING MANUAL.

> The display requires 3 μsec for information transfer, 35 μsec per point for random positioning, and 0.5 μsec per point for intensification.  In vector, vector continue, increment, and character modes the display only requires 1.5 μsec per point for positioning.

**Comment by philbudne** [comment]
I doubt there's another non-DMA interface for the Type 340
(the PDP-6 interface came as quite a shocker!), but I can't help
wondering if it would be cleaner to do this:

Get rid of ty340_rfd().

Have the Type 344 interface code in kx10_dpy call ty340_cycle.

Have ty340_cycle call ty340_fetch(u->DAC), as it does now, and increment DAC.

Make it a requirement that ty340_fetch call ty340_instruction
(and have ty340_instruction update u->status?), or schedule
ty340_instruction to be called.

Have the Type 344 implementation of ty340_fetch ignore DAC, and return
an 18 bit halfword if one available from the last DATAO, otherwise
request a data interrupt.

If ty340_cycle took the service interval, then it could call
display_age with it, and the interface code wouldn't need to.

NOTE!! I haven't tried any of this!

**Comment by larsbrinkhoff** [comment]
Pull requests #193 and #204 fixes the most glaring issues and makes the 340 a fully usable display for all applications.  So I think this issue can be closed.

There is still room for improvements, but there's no pressing need.
