### ISSUE TITLE
KA10: Performance

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#54]
As the ITS build times keep increasing, I'm starting to eye simulator performance.  Is it appropriate to look for optimizations?

**Comment by larsbrinkhoff** [comment]
One thing I've been thinking about is checking for interrupts.  It seems to be this is done by looping through an 128-element array.  Isn't this done very often, like at least once for every instruction?

Just an observation.  Should really use profiling to look for hotspots.

**Comment by rcornwell** [comment]
Actually this is only done when a device posts and interrupt. Or when the status of the PI system changes. When a set_interrupt() call is made pi_pending is set. If check_irq_level() is called with pi_pending == 0, it exits without further processing. If check_irq_level determines that there are no pending interrupts it will clear pi_pending so that no further processing is done until there is a change.
