### ISSUE TITLE
KA10: ITS ML/DM pager

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#73]
Add a simulator setting for using the ML/DM pager instead of the AI pager.  One less address bit; it's a age bit instead?  (Do you do aging?)

I understand this is hovering right around the barely worth it threshold.  But on the other hand it should be quite easy.  It could be a nice exercise for someone that want's to get started hacking the simulator.

**Comment by rcornwell** [comment]
I'm not sure this is actually needed. Looking at the ITS source it appears that DM pager lacked the B and C memories. This basically gave ITS 2 16K regions in memory that were mapped without going through the TLB. This was transparent to the OS, since any access that could not be done by the B or C memories went through the TLB. This just gave a performance boost to small applications.

I do not implement the B+C memories in my pager, to actually implement them would slow things down since I would first have to check if the access were to B or C memories before looking in the TLB. Right now I take the page and map it into the TLB page, if it is not there I load it. Once loaded there is little overhead for a page fault. One option might be to preload the B and C memory ranges, but not sure how much of a gain that would be.

I am thinking we can skip this addition.

**Comment by larsbrinkhoff** [comment]
As I wrote, barely worth it.  If it turns out to be useful some day, I can reopen or submit a pull request.
